FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY apps/frontend/package*.json ./apps/frontend/
COPY packages/shared-types/package*.json ./packages/shared-types/

RUN npm ci

COPY packages/shared-types ./packages/shared-types
COPY apps/frontend ./apps/frontend

RUN npm run build --workspace=@prowexa/shared-types
RUN npm run build --workspace=@prowexa/frontend

FROM nginx:alpine AS runner

COPY --from=builder /app/apps/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
